spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taco_cloud
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080
logging:
  level:
    root: info